language: cpp

#sudo: false
sudo: required
dist: trusty

#addons:
#    apt:
#        packages:
#            - gcc-4.8
#            - g++-4.8

compiler: g++

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make
    - bin/ngmlr*/ngmlr -h


